# -*- coding: utf-8 -*-
"""models.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LbHp1g6-xwoUN6zQGIehi-GAJXqZfKqm
"""

!pip install boto3
!pip install psycopg2

import json
import urllib.request
from datetime import datetime
import boto3
import psycopg2

"""The process_image() method code defines a function named process_image that takes 3 arguments

 camera_ids : *a list of camera ids*

 phenomenon_time: *a string representing a timestamp*

 model_endpoint: *a string representing the name of a endpoint*

 The function first establishes a database connection to a database hosted on an Amazon RDS instance using the psycopg2 library. 

 The database connection string is stored in a variable named conn_string.

 Then, for each camera_id in the camera_ids list, the function retrieves an image from a specific URL using the urllib library. 

 The image data is stored in a variable named image.







"""

def count_vehicles(event,context):
  phenomenon_time=datetime.now()
  camera_ids=[122,107,129,95,36,75,26,32]
  process_image(camera_ids,phenomenon_time,'vehicle-model-endpont')

def count_human(event,context):
  phenomenon_time=datetime.now()
  camera_ids=[122,107,129,95,36,75,26,32]
  process_image(camera_ids,phenomenon_time,'human-model-endpont')

def count_bikes(event, context):
    phenomenon_time = datetime.now()
    camera_ids = [122, 107, 129, 95, 36, 75, 26, 32]
    process_image(camera_ids, phenomenon_time, 'bike-model-endpoint')